system:
  max-work-threads: 3
  max-work-process: 4
  max-migration-threads: 2
  max-migration-process: 4
report:
  report-path: D:\data\report
  migration-result: D:\data\migration-result
  local-test-data-path: D:\data\mindex # windows 일 경우에만 동작한다.
logging:
  log-path: D:\data\log
  file-log-level: INFO # DEBUG, MINOR, INFO, ERROR
  stdout-log-level: INFO # DEBUG, MINOR, INFO, ERROR
  max-logfile-size: 10240 # MB
mail:
  final-check-method: md5sum # md5sum, size, none (default: size)
  enable-hardlink: true
  partition-capacity-threshold-ratio: 90
  move-strategy: REMAINING_CAPACITY_LOWER_PRIORITY # ROUND_ROBIN, REMAINING_CAPACITY_LOWER_PRIORITY, REMAINING_CAPACITY_HIGHER_PRIORITY
  path:
    mindex-path: D:\data\mindex\opt\TerraceTims\mindex # 스캔용도, 이관시에는 DB값 참조해서 찾는다.
    #origin-mdata-path: D:\data\mindex\opt\TerraceTims\mdata
    #new-mdata-path: D:\data\mindex\opt\TerraceTims\new_mdata
    origin-mdata-path: D:\data\mindex\opt\TerraceTims\new_mdata
    new-mdata-path: D:\data\mindex\opt\TerraceTims\mdata
database:
  postgresql:
    host: 172.22.1.103
    port: 5432
    username: mailadm
    password: pgadmin80!@
    database: do
date-range:
  #start-day: 2022-03-01 # 이관 시작일 : ex> 2022.01.01, null 일 경우, 종료일 이전 모든 시간에 대해서 작업 ()
  #end-day: 2022-09-01   # 이관 종료일 : ex> 2022.08.32, null 일 경우, 현재시간
