database:
  postgresql:
    host: 10.0.1.251
    port: 5432
    username: mailadm
    password: pgadmin80!@
    database: tims

date_range:
  start_day: 2022-03-01 # 이관 시작일 : ex> 2022.01.01, null 일 경우, 종료일 이전 모든 시간에 대해서 작업
  end_day: 2022-09-01   # 이관 종료일 : ex> 2022.08.32, Not null
