system:
  max-work-threads: 12
report:
  report-path: /opt/mail-migration-data/report
  migration-result: /opt/mail-migration-data/migration-result
logging:
  log-path: /opt/mail-migration-data/log
  file-log-level: INFO # DEBUG, MINOR, INFO, ERROR
  stdout-log-level: INFO # DEBUG, MINOR, INFO, ERROR
  max-logfile-size: 10240 # MB
mail:
  partition-capacity-threshold-ratio: 90
  move-strategy: ROUND_ROBIN # ROUND_ROBIN, REMAINING_CAPACITY_LOWER_PRIORITY, REMAINING_CAPACITY_HIGHER_PRIORITY
  path:
    origin-mdata-path: "
                      /data/mdata,
                      /data/mdata2,
                      /data/mdata3,
                      /data/mdata4,
                      /data/mdata5,
                      /data/mdata6
    "
    new-mdata-path: "
                    /data/new_mdata/mdata10,
                    /data/new_mdata/mdata11,
                    /data/new_mdata/mdata12,
                    /data/new_mdata/mdata13,
                    /data/new_mdata/mdata14,
                    /data/new_mdata/mdata15
    "
database:
  postgresql:
    host: 10.0.1.251
    port: 5432
    username: mailadm
    password: pgadmin80!@
    database: tims